### ISSUE TITLE
How to use with yaml based pipelines?

### ISSUE THREAD

**Issue by StephenHodgson** [renevanosnabrugge/SendEmail-BuildTask#37]
We're not using the classic pipelines, but the yaml based ones.

How could we take advantage of this task in yaml?

**Comment by hangy** [comment]
I just copied the syntax from an old release pipeline:
```yaml
        steps:
          - task: rvo.SendEmailTask.send-email-build-task.SendEmail@1
            inputs:
              To: "recipient@example.org"
              From: "sender@example.org"
              Subject: New release $(Build.Repository.Name) Version $(Build.BuildNumber)
              Body: |
                $(Build.SourceVersionMessage)
              SmtpServer: smtp.example.org
              SmtpPort: 25
              UseSSL: false
```

**Comment by arpitmishra-eaton** [comment]
could @hangy please help me with SmtpServer configuration ? i mean what exactly we need to put here when we running in windows agent?

**Comment by hangy** [comment]
> could @hangy please help me with SmtpServer configuration ? i mean what exactly we need to put here when we running in windows agent?

Just use any SMTP server that you have in your network. If you don't have any, you can probably also use something like gmail (untested).

```yaml
        steps:
          - task: rvo.SendEmailTask.send-email-build-task.SendEmail@1
            inputs:
              To: "recipient@example.org"
              From: "example@gmail.com"
              Subject: New release $(Build.Repository.Name) Version $(Build.BuildNumber)
              Body: |
                $(Build.SourceVersionMessage)
              SmtpServer: smtp.gmail.com
              SmtpPort: 587
              SmtpUsername: example@gmail.com
              SmtpPassword: $(GmailPassword)
              UseSSL: true
```
